#!/usr/bin/env python3
"""Generate src/api.py from the Brushfire OpenAPI spec."""

import os
import re
import subprocess
import sys
import urllib.parse
import urllib.request
import json
from collections import defaultdict
from typing import Dict, List, Optional, Set, Tuple

BASE_URL = ""


def load_config() -> Tuple[str, str, str, str, str]:
    """Read swagger URL, output path, and test output path from pyproject.toml."""
    import toml
    with open("pyproject.toml") as fh:
        config = toml.load(fh)
    url = config["tool"]["datamodel-codegen"]["url"]
    output = config["tool"]["generate-api"]["output"]
    test_output = config["tool"]["generate-api"]["test-output"]
    parsed = urllib.parse.urlparse(url)
    base_url = f"{parsed.scheme}://{parsed.netloc}"
    # extract version from path, e.g. /swagger/2025-07-22/swagger.json -> 2025-07-22
    api_version = parsed.path.split("/")[2]
    return url, base_url, output, test_output, api_version


def ref_to_name(ref: str) -> str:
    """Extract model class name from a $ref string."""
    return ref.split("/")[-1]


def resolve_type(schema: dict, components: dict) -> str:
    """Convert an OpenAPI schema to a Python type annotation string."""
    if not schema:
        return "Any"
    if "$ref" in schema:
        return ref_to_name(schema["$ref"])
    kind = schema.get("type")
    if kind == "array":
        inner = resolve_type(schema.get("items", {}), components)
        return f"List[{inner}]"
    if kind == "string":
        fmt = schema.get("format", "")
        if fmt == "uuid":
            return "str"
        if fmt in ("date-time", "date"):
            return "str"
        return "str"
    if kind == "integer":
        return "int"
    if kind == "number":
        return "float"
    if kind == "boolean":
        return "bool"
    if kind == "object":
        return "Dict[str, Any]"
    return "Any"


def get_response_type(op: dict, components: dict) -> str:
    """Return the Python type for the 200 response body, or None."""
    resp = op.get("responses", {}).get("200", {})
    content = resp.get("content", {})
    schema = (
        content.get("application/json", {}).get("schema")
        or content.get("text/json", {}).get("schema")
    )
    if not schema:
        return "None"
    return resolve_type(schema, components)


def get_body_type(op: dict) -> Optional[str]:
    """Return the model name for the request body, or None."""
    body = op.get("requestBody", {})
    content = body.get("content", {})
    schema = (
        content.get("application/json", {}).get("schema")
        or content.get("text/json", {}).get("schema")
    )
    if not schema:
        return None
    if "$ref" in schema:
        return ref_to_name(schema["$ref"])
    return None


def path_to_func_name(method: str, path: str, op: dict) -> str:
    """Derive a snake_case function name from method + path."""
    op_id = op.get("operationId", "")
    if op_id:
        # operationId is usually like "AccessCodes_List" or "AccessCodes_Create"
        name = re.sub(r"[^a-zA-Z0-9]", "_", op_id).lower()
        return re.sub(r"_+", "_", name).strip("_")
    # Fallback: build from method + path segments
    parts = [method.lower()]
    for seg in path.strip("/").split("/"):
        if seg.startswith("{") and seg.endswith("}"):
            parts.append("by_" + seg[1:-1].lower())
        else:
            parts.append(seg.replace("-", "_").lower())
    return "_".join(parts)


def collect_models_used(data: dict) -> Set[str]:
    """Walk all operations and collect every model name referenced."""
    primitives = {"None", "Any", "str", "int", "float", "bool", "Dict[str, Any]"}
    names = set()  # type: Set[str]
    components = data.get("components", {})
    for path, ops in data["paths"].items():
        for method, op in ops.items():
            ret = get_response_type(op, components)
            inner = ret.replace("List[", "").replace("]", "")
            if inner not in primitives:
                names.add(inner)
            body = get_body_type(op)
            if body:
                names.add(body)
            for p in op.get("parameters", []):
                ptype = resolve_type(p.get("schema", {}), components)
                inner = ptype.replace("List[", "").replace("]", "")
                if inner not in primitives:
                    names.add(inner)
    return names


def generate(data: dict, api_version: str = "") -> str:
    components = data.get("components", {})
    model_names = collect_models_used(data)

    lines = []  # type: List[str]

    lines.append("# generated by generate_api.py — do not edit by hand")
    lines.append("from typing import Any, Dict, List, Optional")
    lines.append("")
    lines.append("import httpx")
    lines.append("")
    if model_names:
        sorted_names = sorted(model_names)
        lines.append("from brushfire_api.models import (")
        for name in sorted_names:
            lines.append(f"    {name},")
        lines.append(")")
    lines.append("")
    lines.append("")
    lines.append("class BrushfireClient:")
    lines.append(f'    BASE_URL = "{BASE_URL}"')
    lines.append("")
    lines.append("    def __init__(self, api_key: str) -> None:")
    lines.append("        self._client = httpx.Client(")
    lines.append('            base_url=self.BASE_URL,')
    lines.append(f'            headers={{"Authorization": api_key, "api-version": "{api_version}"}},')
    lines.append("        )")
    lines.append("")

    # Group by tag for readability (comments only)
    by_tag = defaultdict(list)  # type: Dict[str, list]
    for path, ops in data["paths"].items():
        for method, op in ops.items():
            tag = op.get("tags", ["Misc"])[0]
            by_tag[tag].append((method, path, op))

    for tag in sorted(by_tag.keys()):
        lines.append(f"    # --- {tag} ---")
        lines.append("")
        for method, path, op in by_tag[tag]:
            func_name = path_to_func_name(method, path, op)
            ret_type = get_response_type(op, components)
            body_type = get_body_type(op)

            # Build parameter list
            params = []  # type: List[str]
            path_params = [p for p in op.get("parameters", []) if p["in"] == "path"]
            query_params = [p for p in op.get("parameters", []) if p["in"] == "query"]

            for p in path_params:
                py_type = resolve_type(p.get("schema", {}), components)
                params.append(f"{p['name']}: {py_type}")
            if body_type:
                params.append(f"body: {body_type}")
            for p in query_params:
                py_type = resolve_type(p.get("schema", {}), components)
                required = p.get("required", False)
                if required:
                    params.append(f"{p['name']}: {py_type}")
                else:
                    params.append(f"{p['name']}: Optional[{py_type}] = None")

            param_str = ", ".join(["self"] + params)
            lines.append(f"    def {func_name}({param_str}) -> {ret_type}:")

            summary = op.get("summary", "")
            if summary:
                lines.append(f'        """{summary}"""')

            # Build URL
            url_path = re.sub(r"\{(\w+)\}", r"{\1}", path)
            if path_params:
                lines.append(f'        url = f"{url_path}"')
            else:
                lines.append(f'        url = "{url_path}"')

            # Build kwargs
            call_parts = ["url"]  # type: List[str]
            if query_params:
                qp_items = ", ".join(
                    f'"{p["name"]}": {p["name"]}' for p in query_params
                )
                lines.append(
                    f"        params = {{{qp_items}}}"
                )
                lines.append(
                    "        params = {k: v for k, v in params.items() if v is not None}"
                )
                call_parts.append("params=params")
            if body_type:
                call_parts.append("json=body.dict(exclude_none=True)")

            call = f"self._client.{method}({', '.join(call_parts)})"
            lines.append(f"        response = {call}")
            lines.append("        response.raise_for_status()")

            # Return value
            if ret_type == "None":
                lines.append("        return None")
            elif ret_type.startswith("List["):
                inner = ret_type[5:-1]
                if inner in ("str", "int", "float", "bool", "Any"):
                    lines.append("        return response.json()")
                else:
                    lines.append(
                        f"        return [{inner}.parse_obj(item) for item in response.json()]"
                    )
            else:
                if ret_type in ("str", "int", "float", "bool", "Any", "Dict[str, Any]"):
                    lines.append("        return response.json()")
                else:
                    lines.append(f"        return {ret_type}.parse_obj(response.json())")

            lines.append("")

    return "\n".join(lines)


def _dummy_arg(schema: dict, components: dict) -> str:
    """Return a sensible literal argument for a parameter in a test call."""
    if not schema:
        return '"test"'
    if "$ref" in schema:
        return '"test"'
    kind = schema.get("type", "string")
    fmt = schema.get("format", "")
    if fmt == "uuid":
        return '"00000000-0000-0000-0000-000000000000"'
    if kind == "integer":
        return "1"
    if kind == "number":
        return "1.0"
    if kind == "boolean":
        return "True"
    return '"test"'


def generate_tests(data: dict) -> str:
    components = data.get("components", {})

    lines = []  # type: List[str]

    lines.append("# generated by generate_api.py — do not edit by hand")
    lines.append("import pytest")
    lines.append("from unittest.mock import MagicMock")
    lines.append("from brushfire_api.api import BrushfireClient")
    lines.append("")
    lines.append("")
    lines.append("@pytest.fixture")
    lines.append("def client():")
    lines.append('    c = BrushfireClient("test-key")')
    lines.append("    c._client = MagicMock()")
    lines.append("    return c")
    lines.append("")

    by_tag = defaultdict(list)  # type: Dict[str, list]
    for path, ops in data["paths"].items():
        for method, op in ops.items():
            tag = op.get("tags", ["Misc"])[0]
            by_tag[tag].append((method, path, op))

    for tag in sorted(by_tag.keys()):
        class_name = "Test" + re.sub(r"[^a-zA-Z0-9]", "", tag)
        lines.append("")
        lines.append(f"class {class_name}:")

        for method, path, op in by_tag[tag]:
            func_name = path_to_func_name(method, path, op)
            ret_type = get_response_type(op, components)
            body_type = get_body_type(op)

            path_params = [p for p in op.get("parameters", []) if p["in"] == "path"]
            query_params = [p for p in op.get("parameters", []) if p["in"] == "query"]

            lines.append("")
            lines.append(f"    def test_{func_name}(self, client):")

            # Set up mock return value
            if ret_type == "None":
                lines.append(f"        client._client.{method}.return_value.json.return_value = None")
            elif ret_type.startswith("List["):
                lines.append(f"        client._client.{method}.return_value.json.return_value = []")
            else:
                lines.append(f"        client._client.{method}.return_value.json.return_value = {{}}")

            # Build call args
            call_args = []  # type: List[str]
            for p in path_params:
                call_args.append(_dummy_arg(p.get("schema", {}), components))
            if body_type:
                call_args.append("MagicMock()")
            for p in query_params:
                if p.get("required", False):
                    call_args.append(_dummy_arg(p.get("schema", {}), components))

            lines.append(f"        client.{func_name}({', '.join(call_args)})")

            # Assert the right HTTP method was called with the right path
            url_path = path
            for p in path_params:
                url_path = url_path.replace("{" + p["name"] + "}", _dummy_arg(p.get("schema", {}), components).strip('"'))
            lines.append(f'        client._client.{method}.assert_called_once()')
            lines.append(f'        assert client._client.{method}.call_args[0][0] == "{url_path}"')

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    print("Running datamodel-codegen ...")
    result = subprocess.run(["datamodel-codegen"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode != 0:
        print(result.stderr.decode())
        sys.exit(result.returncode)

    swagger_url, base_url, output, test_output, api_version = load_config()
    global BASE_URL
    BASE_URL = base_url
    print(f"Fetching {swagger_url} ...")
    raw = urllib.request.urlopen(swagger_url).read()
    data = json.loads(raw)
    print(f"Generating {output} ...")
    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w") as fh:
        fh.write(generate(data, api_version))
    print(f"Generating {test_output} ...")
    os.makedirs(os.path.dirname(test_output), exist_ok=True)
    with open(test_output, "w") as fh:
        fh.write(generate_tests(data))
    print("Done.")


if __name__ == "__main__":
    main()
