# generated by generate_api.py — do not edit by hand
from typing import Any, Dict, List, Optional

import httpx

from brushfire_api.models import (
    AccessCodeCreateInput,
    AccessCodeCreateOutput,
    AccessCodeKind,
    AccessCodeOutput,
    AccountAuthInput,
    AccountAuthOutput,
    AccountHelpdeskOutput,
    AccountSingleOutput,
    AttendeeCancelInput,
    AttendeeCodeInput,
    AttendeeCommunityInput,
    AttendeeCommunityOutput,
    AttendeeCompletedInput,
    AttendeeDetailsOutput,
    AttendeeDonateInput,
    AttendeeGroupInput,
    AttendeeHelpdeskOutput,
    AttendeeLinkInput,
    AttendeeNumbersToIdsInput,
    AttendeeNumbersToIdsOutput,
    AttendeePrintInput,
    AttendeeTypeCategory,
    AttendeeUpdateGiftInput,
    AttendeeUpdateGiftOutput,
    AttendeeUpdateTypeInput,
    CartAddAttendeeInput,
    CartAddAttendeeOutput,
    CartAddPromotionInput,
    CartAttendeeFormInput,
    CartAttendeeOutput,
    CartDeleteAttendeeOutput,
    CartDeleteEventOutput,
    CartDeletePromotionOutput,
    CartEventOutput,
    CartIdOutput,
    CartLookupOutput,
    CartPromotionOutput,
    CartUpdateAttendeeInput,
    CartUpdateEventInput,
    ClientListOutput,
    ClientSingleOutput,
    CustomQueryGranularity,
    EventCommunityOutput,
    EventCopyInput,
    EventCreateInput,
    EventDetailsOutput,
    EventDocumentOutput,
    EventListOutput,
    EventMoveInput,
    EventPaymentMethodOutput,
    EventResourceOutput,
    EventSeatOutput,
    EventSectionOutput,
    EventSessionOutput,
    EventSingleOutput,
    EventTypeOutput,
    ExchangeInput,
    ExchangeOutput,
    FieldMetaOutput,
    FieldMetaType,
    FieldOutput,
    FieldUpdateInput,
    FieldUpdateType,
    FormOutput,
    GroupCommunityInput,
    GroupCreateInput,
    GroupCreateOutput,
    GroupHelpdeskOutput,
    GroupPrintInput,
    GroupSingleOutput,
    GroupSummaryOutput,
    GroupUpdateInput,
    HookSubscribeInput,
    HookSubscribeOutput,
    HookUnsubscribeInput,
    HookUpdateInput,
    LocationSingleOutput,
    LookupAttendeeResultOutput,
    LookupCreateInput,
    LookupGroupResultOutput,
    LookupOrderResultOutput,
    LookupResultOutput,
    OrderConfirmationResendInput,
    OrderCreateDirectInput,
    OrderCreateInput,
    OrderCreateOutput,
    OrderCreatePOSInput,
    OrderHelpdeskOutput,
    OrderListOutput,
    OrderPrintInput,
    OrderReaderStartInput,
    OrderReaderStartOutput,
    OrderResultOutput,
    OrderSingleOutput,
    OrderSmsInput,
    PaymentProfileListOutput,
    PaymentProfileSingleOutput,
    PrintFormat,
    PrintType,
    PromotionCreateImportInput,
    PromotionCreateInput,
    PromotionCreateOutput,
    PromotionKind,
    PromotionListOutput,
    PromotionSingleOutput,
    RegionDetailOutput,
    RemoteFetchResult,
    SessionAttendeeListOutput,
    SessionAttendeeOutput,
    SessionCheckinMultipleInput,
    SessionCheckinMultipleOutput,
    SessionCheckoutMultipleInput,
    SessionCheckoutMultipleOutput,
    SessionFlexPassCheckinInput,
    SessionFlexPassCheckinOutput,
    SessionFlexPassCheckoutInput,
    SessionFlexPassCheckoutOutput,
    SessionGroupDetailOutput,
    SessionOrderDetailOutput,
    TerminalCreateInput,
    TerminalCreateOutput,
    TerminalOutput,
    ThemeOutput,
    WebhookType,
)


class BrushfireClient:
    BASE_URL = "https://api.brushfire.com"

    def __init__(self, api_key: str) -> None:
        self._client = httpx.Client(
            base_url=self.BASE_URL,
            headers={"Authorization": api_key, "api-version": "2025-07-22"},
        )

    # --- AccessCodes ---

    def get_accesscodes(self, clientId: Optional[str] = None, kind: Optional[AccessCodeKind] = None, isRedeemed: Optional[bool] = None, search: Optional[str] = None) -> List[AccessCodeOutput]:
        """List all access codes for a specific client (and additional parameters)"""
        url = "/accesscodes"
        params = {"clientId": clientId, "kind": kind, "isRedeemed": isRedeemed, "search": search}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [AccessCodeOutput.parse_obj(item) for item in response.json()]

    def get_accesscodes_by_accesscodeid(self, accessCodeId: str) -> AccessCodeOutput:
        """Get details of a single access code"""
        url = f"/accesscodes/{accessCodeId}"
        response = self._client.get(url)
        response.raise_for_status()
        return AccessCodeOutput.parse_obj(response.json())

    def post_accesscodes_dynamic(self, body: AccessCodeCreateInput) -> List[AccessCodeCreateOutput]:
        """Creates the specified quantity of dynamic access codes based upon the provided template code"""
        url = "/accesscodes/dynamic"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [AccessCodeCreateOutput.parse_obj(item) for item in response.json()]

    # --- Accounts ---

    def get_accounts_by_accountid(self, accountId: str) -> AccountSingleOutput:
        """Retrieve information for a specific account"""
        url = f"/accounts/{accountId}"
        response = self._client.get(url)
        response.raise_for_status()
        return AccountSingleOutput.parse_obj(response.json())

    def post_accounts_auth(self, body: AccountAuthInput) -> AccountAuthOutput:
        """Authenticate a user via email and password or social service to get Access Key"""
        url = "/accounts/auth"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AccountAuthOutput.parse_obj(response.json())

    def get_accounts_helpdesk_by_email(self, email: str) -> AccountHelpdeskOutput:
        """Retrieve an account that matches the provided email"""
        url = f"/accounts/helpdesk/{email}"
        response = self._client.get(url)
        response.raise_for_status()
        return AccountHelpdeskOutput.parse_obj(response.json())

    # --- Attendees ---

    def get_attendees_by_attendeeid(self, attendeeId: str, eventId: Optional[str] = None, accessKey: Optional[str] = None, qrSize: Optional[int] = None) -> AttendeeDetailsOutput:
        """Retrieve all relevant attendee information for the given attendee number"""
        url = f"/attendees/{attendeeId}"
        params = {"eventId": eventId, "accessKey": accessKey, "qrSize": qrSize}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def post_attendees_by_attendeeid_cancel(self, attendeeId: str, body: AttendeeCancelInput) -> OrderCreateOutput:
        """Cancel an attendee (zero financial change only)"""
        url = f"/attendees/{attendeeId}/cancel"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderCreateOutput.parse_obj(response.json())

    def post_attendees_by_attendeeid_code(self, attendeeId: str, body: AttendeeCodeInput) -> AttendeeDetailsOutput:
        """Associate an external code with a Brushfire attendee for scanning, etc."""
        url = f"/attendees/{attendeeId}/code"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def get_attendees_by_attendeeid_communities(self, attendeeId: str, accessKey: Optional[str] = None) -> List[AttendeeCommunityOutput]:
        """Gets all the available communities for this specific attendee based upon any rules that might be in place"""
        url = f"/attendees/{attendeeId}/communities"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [AttendeeCommunityOutput.parse_obj(item) for item in response.json()]

    def post_attendees_by_attendeeid_community(self, attendeeId: str, body: AttendeeCommunityInput) -> AttendeeDetailsOutput:
        """Set or clear the community for the specified attendee (as long as the group's community doesn't override)"""
        url = f"/attendees/{attendeeId}/community"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def post_attendees_by_attendeeid_completed(self, attendeeId: str, body: AttendeeCompletedInput) -> AttendeeDetailsOutput:
        """Set a registered attendee's completed state"""
        url = f"/attendees/{attendeeId}/completed"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def get_attendees_by_attendeeid_data(self, attendeeId: str) -> None:
        """Returns all data for the specified attendee in the same structure as {eventId}/data"""
        url = f"/attendees/{attendeeId}/data"
        response = self._client.get(url)
        response.raise_for_status()
        return None

    def post_attendees_by_attendeeid_donate(self, attendeeId: str, body: AttendeeDonateInput) -> OrderCreateOutput:
        """Donate back an attendee"""
        url = f"/attendees/{attendeeId}/donate"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderCreateOutput.parse_obj(response.json())

    def get_attendees_by_attendeeid_fields(self, attendeeId: str, accessKey: Optional[str] = None) -> List[FieldOutput]:
        """Retrieve fields for an attendee"""
        url = f"/attendees/{attendeeId}/fields"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def post_attendees_by_attendeeid_fields(self, attendeeId: str, body: FieldUpdateInput) -> List[FieldOutput]:
        """Update fields for an attendee"""
        url = f"/attendees/{attendeeId}/fields"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def get_attendees_by_attendeeid_fieldscustom(self, attendeeId: str, fieldsToInclude: Optional[List[str]] = None, accessKey: Optional[str] = None) -> List[FieldOutput]:
        """Retrieve fields for an attendee"""
        url = f"/attendees/{attendeeId}/fieldscustom"
        params = {"fieldsToInclude": fieldsToInclude, "accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def post_attendees_by_attendeeid_fieldscustom(self, attendeeId: str, body: FieldUpdateInput) -> List[FieldOutput]:
        """Update fields for an attendee"""
        url = f"/attendees/{attendeeId}/fieldscustom"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def post_attendees_by_attendeeid_gift(self, attendeeId: str, body: AttendeeUpdateGiftInput) -> AttendeeUpdateGiftOutput:
        """Set an attendee registration as a gift"""
        url = f"/attendees/{attendeeId}/gift"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeUpdateGiftOutput.parse_obj(response.json())

    def post_attendees_by_attendeeid_group(self, attendeeId: str, body: AttendeeGroupInput) -> AttendeeDetailsOutput:
        """Set or clear the group (and the associated community) for the specified attendee"""
        url = f"/attendees/{attendeeId}/group"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def post_attendees_by_attendeeid_link(self, attendeeId: str, body: AttendeeLinkInput) -> AttendeeDetailsOutput:
        """Copy all fields from the source attendee to the specified attendee and link them together"""
        url = f"/attendees/{attendeeId}/link"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def get_attendees_by_attendeeid_print(self, attendeeId: str, type: Optional[PrintType] = None, format: Optional[PrintFormat] = None, imageDpi: Optional[int] = None) -> List[str]:
        """Retrieve the printable resources for a single attendee"""
        url = f"/attendees/{attendeeId}/print"
        params = {"type": type, "format": format, "imageDpi": imageDpi}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return response.json()

    def post_attendees_by_attendeeid_type(self, attendeeId: str, body: AttendeeUpdateTypeInput) -> OrderCreateOutput:
        """Change an attendee type (zero financial change only)"""
        url = f"/attendees/{attendeeId}/type"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderCreateOutput.parse_obj(response.json())

    def get_attendees_helpdesk_by_email(self, email: str) -> List[AttendeeHelpdeskOutput]:
        """Retrieve attendees that match provided email"""
        url = f"/attendees/helpdesk/{email}"
        response = self._client.get(url)
        response.raise_for_status()
        return [AttendeeHelpdeskOutput.parse_obj(item) for item in response.json()]

    def post_attendees_ids(self, body: AttendeeNumbersToIdsInput) -> AttendeeNumbersToIdsOutput:
        """Convert a list of attendee numbers to their corresponding unique IDs, checking permissions for each"""
        url = "/attendees/ids"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return AttendeeNumbersToIdsOutput.parse_obj(response.json())

    def post_attendees_print(self, body: AttendeePrintInput) -> List[str]:
        """Retrieve the printable resources for multiple attendees"""
        url = "/attendees/print"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    # --- Cart ---

    def get_cart_by_cartid(self, cartId: str, accessKey: Optional[str] = None, pos: Optional[bool] = None, exclude: Optional[str] = None, slipstream: Optional[str] = None, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> List[CartEventOutput]:
        """Retrieve events and attendees for a specific cart"""
        url = f"/cart/{cartId}"
        params = {"accessKey": accessKey, "pos": pos, "exclude": exclude, "slipstream": slipstream, "originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [CartEventOutput.parse_obj(item) for item in response.json()]

    def delete_cart_by_cartid_events_by_eventid(self, cartId: str, eventId: str) -> CartDeleteEventOutput:
        """Delete all attendees for a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}"
        response = self._client.delete(url)
        response.raise_for_status()
        return CartDeleteEventOutput.parse_obj(response.json())

    def get_cart_by_cartid_events_by_eventid(self, cartId: str, eventId: str, accessKey: Optional[str] = None, pos: Optional[bool] = None, exclude: Optional[str] = None, slipstream: Optional[str] = None, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> CartEventOutput:
        """Retrieve event and attendees for a specific cart and specific event"""
        url = f"/cart/{cartId}/events/{eventId}"
        params = {"accessKey": accessKey, "pos": pos, "exclude": exclude, "slipstream": slipstream, "originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return CartEventOutput.parse_obj(response.json())

    def post_cart_by_cartid_events_by_eventid(self, cartId: str, eventId: str, body: CartUpdateEventInput, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> CartEventOutput:
        """Update a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}"
        params = {"originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return CartEventOutput.parse_obj(response.json())

    def post_cart_by_cartid_events_by_eventid_attendees(self, cartId: str, eventId: str, body: CartAddAttendeeInput, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> CartAddAttendeeOutput:
        """Add attendees to the specified cart"""
        url = f"/cart/{cartId}/events/{eventId}/attendees"
        params = {"originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return CartAddAttendeeOutput.parse_obj(response.json())

    def delete_cart_by_cartid_events_by_eventid_attendees_by_attendeeid(self, cartId: str, eventId: str, attendeeId: str) -> CartDeleteAttendeeOutput:
        """Delete a specific attendee from a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/attendees/{attendeeId}"
        response = self._client.delete(url)
        response.raise_for_status()
        return CartDeleteAttendeeOutput.parse_obj(response.json())

    def get_cart_by_cartid_events_by_eventid_attendees_by_attendeeid(self, cartId: str, eventId: str, attendeeId: str, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> CartAttendeeOutput:
        """Retrieve information for a specific attendee in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/attendees/{attendeeId}"
        params = {"originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return CartAttendeeOutput.parse_obj(response.json())

    def post_cart_by_cartid_events_by_eventid_attendees_by_attendeeid(self, cartId: str, eventId: str, attendeeId: str, body: CartUpdateAttendeeInput, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> CartAttendeeOutput:
        """Update information for a specific attendee in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/attendees/{attendeeId}"
        params = {"originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return CartAttendeeOutput.parse_obj(response.json())

    def get_cart_by_cartid_events_by_eventid_attendees_by_attendeeid_form(self, cartId: str, eventId: str, attendeeId: str, accessKey: Optional[str] = None, originalOrderId: Optional[str] = None) -> FormOutput:
        """Retrieve form for a specific attendee for a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/attendees/{attendeeId}/form"
        params = {"accessKey": accessKey, "originalOrderId": originalOrderId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return FormOutput.parse_obj(response.json())

    def post_cart_by_cartid_events_by_eventid_attendees_by_attendeeid_form(self, cartId: str, eventId: str, attendeeId: str, body: CartAttendeeFormInput, originalOrderId: Optional[str] = None) -> FormOutput:
        """Update form for a specific attendee for a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/attendees/{attendeeId}/form"
        params = {"originalOrderId": originalOrderId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return FormOutput.parse_obj(response.json())

    def get_cart_by_cartid_events_by_eventid_form(self, cartId: str, eventId: str, accessKey: Optional[str] = None, originalOrderId: Optional[str] = None) -> FormOutput:
        """Retrieve form for the buyer for a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/form"
        params = {"accessKey": accessKey, "originalOrderId": originalOrderId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return FormOutput.parse_obj(response.json())

    def post_cart_by_cartid_events_by_eventid_form(self, cartId: str, eventId: str, body: FieldUpdateInput, originalOrderId: Optional[str] = None) -> FormOutput:
        """Update form for the buyer for a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/form"
        params = {"originalOrderId": originalOrderId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return FormOutput.parse_obj(response.json())

    def get_cart_by_cartid_events_by_eventid_forms(self, cartId: str, eventId: str, accessKey: Optional[str] = None, originalOrderId: Optional[str] = None) -> List[FormOutput]:
        """Retrieve forms for the buyer and attendees for a specific event in a specific cart"""
        url = f"/cart/{cartId}/events/{eventId}/forms"
        params = {"accessKey": accessKey, "originalOrderId": originalOrderId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [FormOutput.parse_obj(item) for item in response.json()]

    def get_cart_by_cartid_lookup(self, cartId: str, name: Optional[str] = None) -> List[CartLookupOutput]:
        """Search customer accounts and past orders for checkout information for specified cart"""
        url = f"/cart/{cartId}/lookup"
        params = {"name": name}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [CartLookupOutput.parse_obj(item) for item in response.json()]

    def post_cart_by_cartid_promotions(self, cartId: str, body: CartAddPromotionInput, originalOrderId: Optional[str] = None, exchangeId: Optional[str] = None) -> List[CartPromotionOutput]:
        """Adds a promotion (by name) to a specific cart"""
        url = f"/cart/{cartId}/promotions"
        params = {"originalOrderId": originalOrderId, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [CartPromotionOutput.parse_obj(item) for item in response.json()]

    def delete_cart_by_cartid_promotions_by_promotionid(self, cartId: str, promotionId: str) -> CartDeletePromotionOutput:
        """Delete a promotion from a specific cart"""
        url = f"/cart/{cartId}/promotions/{promotionId}"
        response = self._client.delete(url)
        response.raise_for_status()
        return CartDeletePromotionOutput.parse_obj(response.json())

    def get_cart_id(self) -> CartIdOutput:
        """Retreive a system-generated CartId for use in other calls"""
        url = "/cart/id"
        response = self._client.get(url)
        response.raise_for_status()
        return CartIdOutput.parse_obj(response.json())

    # --- Clients ---

    def get_clients(self, accessKey: Optional[str] = None) -> List[ClientListOutput]:
        """Get a list of all clients available to this application"""
        url = "/clients"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [ClientListOutput.parse_obj(item) for item in response.json()]

    def get_clients_by_clientid(self, clientId: str) -> ClientSingleOutput:
        """Get the details for a specific client"""
        url = f"/clients/{clientId}"
        response = self._client.get(url)
        response.raise_for_status()
        return ClientSingleOutput.parse_obj(response.json())

    def get_clients_by_clientid_theme(self, clientId: str, urlKey: Optional[str] = None) -> ThemeOutput:
        """Get the theme for a specific client"""
        url = f"/clients/{clientId}/theme"
        params = {"urlKey": urlKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return ThemeOutput.parse_obj(response.json())

    # --- Data ---

    def get_data_by_id(self, id: str, eventNumber: Optional[int] = None, granularity: Optional[CustomQueryGranularity] = None, startsAt: Optional[str] = None, endsAt: Optional[str] = None) -> None:
        """Returns specialized data from custom-written queries"""
        url = f"/data/{id}"
        params = {"eventNumber": eventNumber, "granularity": granularity, "startsAt": startsAt, "endsAt": endsAt}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return None

    # --- Events ---

    def get_events(self, accessKey: Optional[str] = None, search: Optional[str] = None, inactive: Optional[bool] = None, qty: Optional[int] = None, skip: Optional[int] = None, archive: Optional[bool] = None) -> List[EventListOutput]:
        """Get a list of events for the specified user."""
        url = "/events"
        params = {"accessKey": accessKey, "search": search, "inactive": inactive, "qty": qty, "skip": skip, "archive": archive}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventListOutput.parse_obj(item) for item in response.json()]

    def post_events(self, body: EventCreateInput) -> EventDetailsOutput:
        """Create a fully complete event"""
        url = "/events"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return EventDetailsOutput.parse_obj(response.json())

    def delete_events_by_eventid(self, eventId: str, accessKey: Optional[str] = None) -> bool:
        """Delete an event"""
        url = f"/events/{eventId}"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.delete(url, params=params)
        response.raise_for_status()
        return response.json()

    def get_events_by_eventid(self, eventId: str) -> EventSingleOutput:
        """Retrieve information for an event"""
        url = f"/events/{eventId}"
        response = self._client.get(url)
        response.raise_for_status()
        return EventSingleOutput.parse_obj(response.json())

    def post_events_by_eventid_archive(self, eventId: str, accessKey: Optional[str] = None) -> bool:
        """Queues the specified event for archiving. Sends an email to user associated with the access key used on completion."""
        url = f"/events/{eventId}/archive"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params)
        response.raise_for_status()
        return response.json()

    def get_events_by_eventid_bestseats(self, eventId: str, quantity: Optional[int] = None, sectionId: Optional[str] = None, accessKey: Optional[str] = None, typeId: Optional[str] = None, groupId: Optional[str] = None, seatCode: Optional[str] = None, nonconsecutive: Optional[bool] = None, basePrice: Optional[float] = None) -> List[EventSeatOutput]:
        """Returns the best available seats that match the supplied parameters for an assigned seat event. Does not reserve them."""
        url = f"/events/{eventId}/bestseats"
        params = {"quantity": quantity, "sectionId": sectionId, "accessKey": accessKey, "typeId": typeId, "groupId": groupId, "seatCode": seatCode, "nonconsecutive": nonconsecutive, "basePrice": basePrice}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventSeatOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_communities(self, eventId: str) -> List[EventCommunityOutput]:
        """Returns all communities for the specified event"""
        url = f"/events/{eventId}/communities"
        response = self._client.get(url)
        response.raise_for_status()
        return [EventCommunityOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_data(self, eventId: str, type: Optional[FieldMetaType] = None, since: Optional[str] = None, includeCancelled: Optional[bool] = None) -> None:
        """Returns all data for the specified type"""
        url = f"/events/{eventId}/data"
        params = {"type": type, "since": since, "includeCancelled": includeCancelled}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return None

    def get_events_by_eventid_details(self, eventId: str, groupId: Optional[str] = None, accessKey: Optional[str] = None, access: Optional[str] = None, exchangeId: Optional[str] = None) -> EventDetailsOutput:
        """Retrieve information for an event"""
        url = f"/events/{eventId}/details"
        params = {"groupId": groupId, "accessKey": accessKey, "access": access, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return EventDetailsOutput.parse_obj(response.json())

    def get_events_by_eventid_documents(self, eventId: str) -> EventDocumentOutput:
        """Get which printing layouts are available for an event"""
        url = f"/events/{eventId}/documents"
        response = self._client.get(url)
        response.raise_for_status()
        return EventDocumentOutput.parse_obj(response.json())

    def get_events_by_eventid_fieldmetadata(self, eventId: str) -> List[FieldMetaOutput]:
        """Get the meta data for ALL fields for an event including the built-in/system ones"""
        url = f"/events/{eventId}/fieldmetadata"
        response = self._client.get(url)
        response.raise_for_status()
        return [FieldMetaOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_fields(self, eventId: str, fieldType: Optional[FieldUpdateType] = None, accessKey: Optional[str] = None) -> List[FieldOutput]:
        """Get fields for an event"""
        url = f"/events/{eventId}/fields"
        params = {"fieldType": fieldType, "accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_fields_by_fieldid_remotevalidate(self, fieldId: str, eventId: str, eventNumber: Optional[int] = None, value: Optional[str] = None, attendeeNumber: Optional[int] = None) -> None:
        """Fetch result for given Remote Valid field when value is provided"""
        url = f"/events/{eventId}/fields/{fieldId}/remotevalidate"
        params = {"eventNumber": eventNumber, "value": value, "attendeeNumber": attendeeNumber}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return None

    def get_events_by_eventid_groups(self, eventId: str, search: Optional[str] = None) -> List[GroupSummaryOutput]:
        """List all groups for an event"""
        url = f"/events/{eventId}/groups"
        params = {"search": search}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [GroupSummaryOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_lookup(self, eventId: str, email: Optional[str] = None) -> List[LookupAttendeeResultOutput]:
        """Look up attendees based upon email for an event"""
        url = f"/events/{eventId}/lookup"
        params = {"email": email}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [LookupAttendeeResultOutput.parse_obj(item) for item in response.json()]

    def post_events_by_eventid_move(self, eventId: str, body: EventMoveInput) -> EventSingleOutput:
        """Move an event to a different client. The event must have no existing orders or emails.
The calling app must have access to both the source and target clients."""
        url = f"/events/{eventId}/move"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return EventSingleOutput.parse_obj(response.json())

    def get_events_by_eventid_orders(self, eventId: str, startsAt: Optional[str] = None, endsAt: Optional[str] = None) -> List[OrderListOutput]:
        """Gets list of orders for an event with an optional date range."""
        url = f"/events/{eventId}/orders"
        params = {"startsAt": startsAt, "endsAt": endsAt}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [OrderListOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_paymentmethods(self, eventId: str, accessKey: Optional[str] = None) -> List[EventPaymentMethodOutput]:
        """Get which payment methods are available for an event"""
        url = f"/events/{eventId}/paymentmethods"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventPaymentMethodOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_reports_by_reportid(self, eventId: str, reportId: str) -> None:
        """Get report data for a custom or preset event report"""
        url = f"/events/{eventId}/reports/{reportId}"
        response = self._client.get(url)
        response.raise_for_status()
        return None

    def get_events_by_eventid_resources(self, eventId: str) -> List[EventResourceOutput]:
        """Get a list of resource urls corresponding to specific Brushfire pages for the event"""
        url = f"/events/{eventId}/resources"
        response = self._client.get(url)
        response.raise_for_status()
        return [EventResourceOutput.parse_obj(item) for item in response.json()]

    def post_events_by_eventid_restore(self, eventId: str, accessKey: Optional[str] = None) -> bool:
        """Queues the specified event for restoring. Sends an email to user associated with the access key used on completion."""
        url = f"/events/{eventId}/restore"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.post(url, params=params)
        response.raise_for_status()
        return response.json()

    def get_events_by_eventid_sections(self, eventId: str, groupId: Optional[str] = None, seatCode: Optional[str] = None) -> List[EventSectionOutput]:
        """Get the details for all the sections of an event"""
        url = f"/events/{eventId}/sections"
        params = {"groupId": groupId, "seatCode": seatCode}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventSectionOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_sections_by_sectionid(self, eventId: str, sectionId: str, groupId: Optional[str] = None, seatCode: Optional[str] = None) -> EventSectionOutput:
        """Get the details for a specific section"""
        url = f"/events/{eventId}/sections/{sectionId}"
        params = {"groupId": groupId, "seatCode": seatCode}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return EventSectionOutput.parse_obj(response.json())

    def get_events_by_eventid_sections_by_sectionid_seats(self, eventId: str, sectionId: str, groupId: Optional[str] = None, seatCode: Optional[str] = None, accessKey: Optional[str] = None) -> List[EventSeatOutput]:
        """Get all the seats in a section for a specific event"""
        url = f"/events/{eventId}/sections/{sectionId}/seats"
        params = {"groupId": groupId, "seatCode": seatCode, "accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventSeatOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_sessions(self, eventId: str, search: Optional[str] = None, includeHidden: Optional[bool] = None) -> List[EventSessionOutput]:
        """Get a list of all of the sessions for an event"""
        url = f"/events/{eventId}/sessions"
        params = {"search": search, "includeHidden": includeHidden}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventSessionOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventid_theme(self, eventId: str) -> ThemeOutput:
        """Get the theme for a specific event"""
        url = f"/events/{eventId}/theme"
        response = self._client.get(url)
        response.raise_for_status()
        return ThemeOutput.parse_obj(response.json())

    def get_events_by_eventid_types(self, eventId: str, group: Optional[str] = None, accessKey: Optional[str] = None, access: Optional[str] = None, seat: Optional[str] = None, category: Optional[AttendeeTypeCategory] = None, exchangeId: Optional[str] = None) -> List[EventTypeOutput]:
        """List all currently available attendee types for a specific event and account (and optionally a specific seat)"""
        url = f"/events/{eventId}/types"
        params = {"group": group, "accessKey": accessKey, "access": access, "seat": seat, "category": category, "exchangeId": exchangeId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [EventTypeOutput.parse_obj(item) for item in response.json()]

    def get_events_by_eventnumber_fields_by_fieldid_remotefetch(self, eventNumber: int, fieldId: str, attendeeNumber: Optional[int] = None, value: Optional[str] = None) -> List[RemoteFetchResult]:
        """Fetch options for given Remote Fetch field when searching a specified value"""
        url = f"/events/{eventNumber}/fields/{fieldId}/remotefetch"
        params = {"attendeeNumber": attendeeNumber, "value": value}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [RemoteFetchResult.parse_obj(item) for item in response.json()]

    def post_events_copy(self, body: EventCopyInput) -> EventSingleOutput:
        """Copy an existing event"""
        url = "/events/copy"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return EventSingleOutput.parse_obj(response.json())

    # --- Exchanges ---

    def post_exchanges(self, body: ExchangeInput) -> ExchangeOutput:
        """Create an exchange"""
        url = "/exchanges"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return ExchangeOutput.parse_obj(response.json())

    def delete_exchanges_by_exchangeid(self, exchangeId: str) -> bool:
        """Deletes an exchange based on the provided exchange ID and client key."""
        url = f"/exchanges/{exchangeId}"
        response = self._client.delete(url)
        response.raise_for_status()
        return response.json()

    def get_exchanges_by_exchangeid(self, exchangeId: str) -> ExchangeOutput:
        """Get full details of an exchange"""
        url = f"/exchanges/{exchangeId}"
        response = self._client.get(url)
        response.raise_for_status()
        return ExchangeOutput.parse_obj(response.json())

    def put_exchanges_by_exchangeid(self, exchangeId: str, body: ExchangeInput) -> ExchangeOutput:
        """Update an exchange"""
        url = f"/exchanges/{exchangeId}"
        response = self._client.put(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return ExchangeOutput.parse_obj(response.json())

    # --- Groups ---

    def post_groups(self, body: GroupCreateInput) -> GroupCreateOutput:
        """Create a group"""
        url = "/groups"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return GroupCreateOutput.parse_obj(response.json())

    def put_groups(self, body: GroupUpdateInput) -> GroupCreateOutput:
        """Update a group"""
        url = "/groups"
        response = self._client.put(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return GroupCreateOutput.parse_obj(response.json())

    def get_groups_by_groupid(self, groupId: str, accessKey: Optional[str] = None, qrSize: Optional[int] = None) -> GroupSingleOutput:
        """Retrieve information about a group"""
        url = f"/groups/{groupId}"
        params = {"accessKey": accessKey, "qrSize": qrSize}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return GroupSingleOutput.parse_obj(response.json())

    def post_groups_by_groupid_community(self, groupId: str, body: GroupCommunityInput) -> GroupCreateOutput:
        """Set or clear the community for the specified group and all of its attendees"""
        url = f"/groups/{groupId}/community"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return GroupCreateOutput.parse_obj(response.json())

    def get_groups_by_groupid_fields(self, groupId: str, accessKey: Optional[str] = None) -> List[FieldOutput]:
        """Retrieve fields for a group"""
        url = f"/groups/{groupId}/fields"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def post_groups_by_groupid_fields(self, groupId: str, body: FieldUpdateInput) -> List[FieldOutput]:
        """Update fields for a group"""
        url = f"/groups/{groupId}/fields"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def get_groups_by_groupid_print(self, groupId: str, type: Optional[PrintType] = None, format: Optional[PrintFormat] = None, imageDpi: Optional[int] = None) -> List[str]:
        """Retrieve the printable resources for a single group"""
        url = f"/groups/{groupId}/print"
        params = {"type": type, "format": format, "imageDpi": imageDpi}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return response.json()

    def get_groups_helpdesk_by_email(self, email: str) -> List[GroupHelpdeskOutput]:
        """Retrieve groups that match provided email"""
        url = f"/groups/helpdesk/{email}"
        response = self._client.get(url)
        response.raise_for_status()
        return [GroupHelpdeskOutput.parse_obj(item) for item in response.json()]

    def post_groups_print(self, body: GroupPrintInput) -> List[str]:
        """Retrieve the printable resources for multiple groups"""
        url = "/groups/print"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    # --- Hooks ---

    def get_hooks_list(self) -> List[HookSubscribeOutput]:
        """For 3rd party and custom integrations to list hooks subscribed by appKey"""
        url = "/hooks/list"
        response = self._client.get(url)
        response.raise_for_status()
        return [HookSubscribeOutput.parse_obj(item) for item in response.json()]

    def get_hooks_ping(self) -> List[Any]:
        """For 3rd party and custom integrations to test connectivity after authentication"""
        url = "/hooks/ping"
        response = self._client.get(url)
        response.raise_for_status()
        return response.json()

    def get_hooks_poll(self, type: Optional[WebhookType] = None, eventId: Optional[str] = None) -> None:
        """For 3rd party and custom integrations to view shape for `data` property of POST from Brushfire"""
        url = "/hooks/poll"
        params = {"type": type, "eventId": eventId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return None

    def get_hooks_sample(self, type: Optional[WebhookType] = None, eventId: Optional[str] = None) -> None:
        """For 3rd party and custom integrations to view shape for `data` property of POST from Brushfire"""
        url = "/hooks/sample"
        params = {"type": type, "eventId": eventId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return None

    def post_hooks_subscribe(self, body: HookSubscribeInput) -> None:
        """For 3rd party and custom integrations to subscribe to our notifications"""
        url = "/hooks/subscribe"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return None

    def post_hooks_unsubscribe(self, body: HookUnsubscribeInput) -> bool:
        """For 3rd party and custom integrations to unsubscribe from our notifications"""
        url = "/hooks/unsubscribe"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    def put_hooks_update(self, body: HookUpdateInput) -> HookSubscribeOutput:
        """For 3rd party and custom integrations to update objects on existing subscriptions"""
        url = "/hooks/update"
        response = self._client.put(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return HookSubscribeOutput.parse_obj(response.json())

    # --- Lookups ---

    def post_lookups(self, body: LookupCreateInput) -> bool:
        """Submit email to look up and create magic link"""
        url = "/lookups"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    def get_lookups_by_lookupid(self, lookupId: str) -> LookupResultOutput:
        """Get matching events for a lookup ID"""
        url = f"/lookups/{lookupId}"
        response = self._client.get(url)
        response.raise_for_status()
        return LookupResultOutput.parse_obj(response.json())

    def get_lookups_by_lookupid_events_by_eventnumber(self, lookupId: str, eventNumber: int) -> LookupResultOutput:
        """Get matching single event for a lookup ID and eventNumber"""
        url = f"/lookups/{lookupId}/events/{eventNumber}"
        response = self._client.get(url)
        response.raise_for_status()
        return LookupResultOutput.parse_obj(response.json())

    def get_lookups_by_lookupid_events_by_eventnumber_attendees(self, lookupId: str, eventNumber: int, includeGroups: Optional[bool] = None, includeOrders: Optional[bool] = None) -> List[LookupAttendeeResultOutput]:
        """Get attendees for the selected lookup ID and eventNumber. This optionally looks across groups and orders also"""
        url = f"/lookups/{lookupId}/events/{eventNumber}/attendees"
        params = {"includeGroups": includeGroups, "includeOrders": includeOrders}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [LookupAttendeeResultOutput.parse_obj(item) for item in response.json()]

    def get_lookups_by_lookupid_events_by_eventnumber_group(self, lookupId: str, eventNumber: int) -> LookupGroupResultOutput:
        """Get group for the selected lookup ID and eventNumber"""
        url = f"/lookups/{lookupId}/events/{eventNumber}/group"
        response = self._client.get(url)
        response.raise_for_status()
        return LookupGroupResultOutput.parse_obj(response.json())

    def get_lookups_by_lookupid_events_by_eventnumber_orders(self, lookupId: str, eventNumber: int) -> List[LookupOrderResultOutput]:
        """Get orders for the selected lookup ID and eventNumber"""
        url = f"/lookups/{lookupId}/events/{eventNumber}/orders"
        response = self._client.get(url)
        response.raise_for_status()
        return [LookupOrderResultOutput.parse_obj(item) for item in response.json()]

    # --- Orders ---

    def get_orders(self, eventId: Optional[str] = None, startsAt: Optional[str] = None, endsAt: Optional[str] = None) -> List[OrderListOutput]:
        """Gets list of orders by eventId and/or a date range."""
        url = "/orders"
        params = {"eventId": eventId, "startsAt": startsAt, "endsAt": endsAt}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [OrderListOutput.parse_obj(item) for item in response.json()]

    def post_orders(self, body: OrderCreateInput) -> OrderCreateOutput:
        """Create an order from an existing cart"""
        url = "/orders"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderCreateOutput.parse_obj(response.json())

    def get_orders_by_orderid(self, orderId: str, accessKey: Optional[str] = None, qrSize: Optional[int] = None) -> OrderSingleOutput:
        """Retrieve a single order"""
        url = f"/orders/{orderId}"
        params = {"accessKey": accessKey, "qrSize": qrSize}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return OrderSingleOutput.parse_obj(response.json())

    def get_orders_by_orderid_fields(self, orderId: str, accessKey: Optional[str] = None) -> List[FieldOutput]:
        """Retrieve fields for an order"""
        url = f"/orders/{orderId}/fields"
        params = {"accessKey": accessKey}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def post_orders_by_orderid_fields(self, orderId: str, body: FieldUpdateInput) -> List[FieldOutput]:
        """Update fields for an order"""
        url = f"/orders/{orderId}/fields"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [FieldOutput.parse_obj(item) for item in response.json()]

    def get_orders_by_orderid_print(self, orderId: str, type: Optional[PrintType] = None, format: Optional[PrintFormat] = None, imageDpi: Optional[int] = None) -> List[str]:
        """Retrieve the printable resources for a single order"""
        url = f"/orders/{orderId}/print"
        params = {"type": type, "format": format, "imageDpi": imageDpi}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return response.json()

    def post_orders_by_orderid_resend(self, orderId: str, body: OrderConfirmationResendInput) -> bool:
        """Resend a confirmation for a single order"""
        url = f"/orders/{orderId}/resend"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    def post_orders_direct(self, body: OrderCreateDirectInput) -> OrderResultOutput:
        """Create cart-less order for free, general admission events with no fields."""
        url = "/orders/direct"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderResultOutput.parse_obj(response.json())

    def get_orders_helpdesk_by_email(self, email: str) -> List[OrderHelpdeskOutput]:
        """Retrieve orders that match provided email"""
        url = f"/orders/helpdesk/{email}"
        response = self._client.get(url)
        response.raise_for_status()
        return [OrderHelpdeskOutput.parse_obj(item) for item in response.json()]

    def post_orders_pos(self, body: OrderCreatePOSInput) -> OrderCreateOutput:
        """Create a point of sale order from an existing cart"""
        url = "/orders/pos"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderCreateOutput.parse_obj(response.json())

    def post_orders_print(self, body: OrderPrintInput) -> List[str]:
        """Retrieve the printable resources for multiple orders"""
        url = "/orders/print"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    def post_orders_reader_start(self, body: OrderReaderStartInput) -> OrderReaderStartOutput:
        """Prepares an order to be paid for with a Square or Stripe Reader."""
        url = "/orders/reader/start"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return OrderReaderStartOutput.parse_obj(response.json())

    def post_orders_sms(self, body: OrderSmsInput) -> bool:
        """Sends SMS messages to the provided phone number (only US and Canada)"""
        url = "/orders/sms"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return response.json()

    # --- PaymentProfiles ---

    def get_paymentprofiles(self, clientId: Optional[str] = None) -> List[PaymentProfileListOutput]:
        """Returns all payment profiles for the specified client"""
        url = "/paymentprofiles"
        params = {"clientId": clientId}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [PaymentProfileListOutput.parse_obj(item) for item in response.json()]

    def get_paymentprofiles_by_paymentprofileid(self, paymentProfileId: str) -> PaymentProfileSingleOutput:
        """Returns the details of the specified payment profile"""
        url = f"/paymentprofiles/{paymentProfileId}"
        response = self._client.get(url)
        response.raise_for_status()
        return PaymentProfileSingleOutput.parse_obj(response.json())

    def get_paymentprofiles_by_paymentprofileid_locations(self, paymentProfileId: str) -> List[LocationSingleOutput]:
        """Returns the locations associated with the merchant ID of a given payment profile."""
        url = f"/paymentprofiles/{paymentProfileId}/locations"
        response = self._client.get(url)
        response.raise_for_status()
        return [LocationSingleOutput.parse_obj(item) for item in response.json()]

    def get_paymentprofiles_by_paymentprofileid_terminals(self, paymentProfileId: str) -> List[TerminalOutput]:
        """Returns all terminals registered to the account associated with the supplied payment profile"""
        url = f"/paymentprofiles/{paymentProfileId}/terminals"
        response = self._client.get(url)
        response.raise_for_status()
        return [TerminalOutput.parse_obj(item) for item in response.json()]

    def post_paymentprofiles_by_paymentprofileid_terminals(self, paymentProfileId: str, body: TerminalCreateInput) -> TerminalCreateOutput:
        """Add a terminal to the supplied payment profile"""
        url = f"/paymentprofiles/{paymentProfileId}/terminals"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return TerminalCreateOutput.parse_obj(response.json())

    # --- Promotions ---

    def get_promotions(self, clientId: Optional[str] = None, kind: Optional[PromotionKind] = None, isRedeemed: Optional[bool] = None, search: Optional[str] = None) -> List[PromotionListOutput]:
        """List all promotions for a specific client (and additional parameters)"""
        url = "/promotions"
        params = {"clientId": clientId, "kind": kind, "isRedeemed": isRedeemed, "search": search}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return [PromotionListOutput.parse_obj(item) for item in response.json()]

    def get_promotions_by_promotionid(self, promotionId: str) -> PromotionSingleOutput:
        """Get details of a single promotion"""
        url = f"/promotions/{promotionId}"
        response = self._client.get(url)
        response.raise_for_status()
        return PromotionSingleOutput.parse_obj(response.json())

    def post_promotions_dynamic(self, body: PromotionCreateInput) -> List[PromotionCreateOutput]:
        """Creates the specified quantity of dynamic promotions based upon the provided template code"""
        url = "/promotions/dynamic"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [PromotionCreateOutput.parse_obj(item) for item in response.json()]

    def post_promotions_import(self, body: PromotionCreateImportInput) -> List[PromotionCreateOutput]:
        """Support for promotion creation based upon provided list of names"""
        url = "/promotions/import"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [PromotionCreateOutput.parse_obj(item) for item in response.json()]

    # --- Regions ---

    def get_regions(self) -> List[RegionDetailOutput]:
        """List all countries and regions with their Code for use in other calls"""
        url = "/regions"
        response = self._client.get(url)
        response.raise_for_status()
        return [RegionDetailOutput.parse_obj(item) for item in response.json()]

    # --- Sessions ---

    def get_sessions_by_sessionid(self, sessionId: str) -> EventSessionOutput:
        """Get detailed information about a given session"""
        url = f"/sessions/{sessionId}"
        response = self._client.get(url)
        response.raise_for_status()
        return EventSessionOutput.parse_obj(response.json())

    def get_sessions_by_sessionid_attendees(self, sessionId: str, search: Optional[str] = None, qty: Optional[int] = None, skip: Optional[int] = None) -> SessionAttendeeListOutput:
        """Get a list of all of the attendees for a given check-in session"""
        url = f"/sessions/{sessionId}/attendees"
        params = {"search": search, "qty": qty, "skip": skip}
        params = {k: v for k, v in params.items() if v is not None}
        response = self._client.get(url, params=params)
        response.raise_for_status()
        return SessionAttendeeListOutput.parse_obj(response.json())

    def post_sessions_by_sessionid_checkin(self, sessionId: str, body: SessionCheckinMultipleInput) -> List[SessionCheckinMultipleOutput]:
        """Check in one or more attendees for a specific session"""
        url = f"/sessions/{sessionId}/checkin"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [SessionCheckinMultipleOutput.parse_obj(item) for item in response.json()]

    def post_sessions_by_sessionid_checkout(self, sessionId: str, body: SessionCheckoutMultipleInput) -> List[SessionCheckoutMultipleOutput]:
        """Check out one or more attendees for a specific session"""
        url = f"/sessions/{sessionId}/checkout"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return [SessionCheckoutMultipleOutput.parse_obj(item) for item in response.json()]

    def get_sessions_by_sessionid_email_by_email(self, email: str, sessionId: int) -> List[SessionAttendeeOutput]:
        """Retrieve attendee data from a specific email and session"""
        url = f"/sessions/{sessionId}/email/{email}"
        response = self._client.get(url)
        response.raise_for_status()
        return [SessionAttendeeOutput.parse_obj(item) for item in response.json()]

    def get_sessions_by_sessionid_flex_by_attendeeid(self, sessionId: str, attendeeId: str) -> AttendeeDetailsOutput:
        """Get detailed information about a given flex attendee in a specific session"""
        url = f"/sessions/{sessionId}/flex/{attendeeId}"
        response = self._client.get(url)
        response.raise_for_status()
        return AttendeeDetailsOutput.parse_obj(response.json())

    def post_sessions_by_sessionid_flex_checkin(self, sessionId: int, body: SessionFlexPassCheckinInput) -> SessionFlexPassCheckinOutput:
        """Checkin a flex pass attendee for a specific session"""
        url = f"/sessions/{sessionId}/flex/checkin"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return SessionFlexPassCheckinOutput.parse_obj(response.json())

    def post_sessions_by_sessionid_flex_checkout(self, sessionId: int, body: SessionFlexPassCheckoutInput) -> SessionFlexPassCheckoutOutput:
        """Check out a flex pass attendee for a specific session"""
        url = f"/sessions/{sessionId}/flex/checkout"
        response = self._client.post(url, json=body.dict(exclude_none=True))
        response.raise_for_status()
        return SessionFlexPassCheckoutOutput.parse_obj(response.json())

    def get_sessions_by_sessionid_groups_by_groupid(self, groupId: str, sessionId: int) -> SessionGroupDetailOutput:
        """Get all details, including checkin info for a group in a given session"""
        url = f"/sessions/{sessionId}/groups/{groupId}"
        response = self._client.get(url)
        response.raise_for_status()
        return SessionGroupDetailOutput.parse_obj(response.json())

    def get_sessions_by_sessionid_orders_by_orderid(self, orderId: str, sessionId: int) -> SessionOrderDetailOutput:
        """Retrieve Order and Buyer data from a specific order and session"""
        url = f"/sessions/{sessionId}/orders/{orderId}"
        response = self._client.get(url)
        response.raise_for_status()
        return SessionOrderDetailOutput.parse_obj(response.json())
