# generated by generate_api.py — do not edit by hand
import pytest
from unittest.mock import MagicMock
from brushfire_api.api import BrushfireClient


@pytest.fixture
def client():
    c = BrushfireClient("test-key")
    c._client = MagicMock()
    return c


class TestAccessCodes:

    def test_get_accesscodes(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_accesscodes()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/accesscodes"

    def test_get_accesscodes_by_accesscodeid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_accesscodes_by_accesscodeid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/accesscodes/test"

    def test_post_accesscodes_dynamic(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_accesscodes_dynamic(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/accesscodes/dynamic"

class TestAccounts:

    def test_get_accounts_by_accountid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_accounts_by_accountid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/accounts/test"

    def test_post_accounts_auth(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_accounts_auth(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/accounts/auth"

    def test_get_accounts_helpdesk_by_email(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_accounts_helpdesk_by_email("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/accounts/helpdesk/test"

class TestAttendees:

    def test_get_attendees_by_attendeeid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_attendees_by_attendeeid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/test"

    def test_post_attendees_by_attendeeid_cancel(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_cancel("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/cancel"

    def test_post_attendees_by_attendeeid_code(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_code("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/code"

    def test_get_attendees_by_attendeeid_communities(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_attendees_by_attendeeid_communities("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/test/communities"

    def test_post_attendees_by_attendeeid_community(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_community("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/community"

    def test_post_attendees_by_attendeeid_completed(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_completed("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/completed"

    def test_get_attendees_by_attendeeid_data(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_attendees_by_attendeeid_data("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/test/data"

    def test_post_attendees_by_attendeeid_donate(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_donate("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/donate"

    def test_get_attendees_by_attendeeid_fields(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_attendees_by_attendeeid_fields("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/test/fields"

    def test_post_attendees_by_attendeeid_fields(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_attendees_by_attendeeid_fields("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/fields"

    def test_get_attendees_by_attendeeid_fieldscustom(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_attendees_by_attendeeid_fieldscustom("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/test/fieldscustom"

    def test_post_attendees_by_attendeeid_fieldscustom(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_attendees_by_attendeeid_fieldscustom("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/fieldscustom"

    def test_post_attendees_by_attendeeid_gift(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_gift("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/gift"

    def test_post_attendees_by_attendeeid_group(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_group("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/group"

    def test_post_attendees_by_attendeeid_link(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_link("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/link"

    def test_get_attendees_by_attendeeid_print(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_attendees_by_attendeeid_print("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/test/print"

    def test_post_attendees_by_attendeeid_type(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_by_attendeeid_type("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/test/type"

    def test_get_attendees_helpdesk_by_email(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_attendees_helpdesk_by_email("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/attendees/helpdesk/test"

    def test_post_attendees_ids(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_attendees_ids(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/ids"

    def test_post_attendees_print(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_attendees_print(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/attendees/print"

class TestCart:

    def test_get_cart_by_cartid(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_cart_by_cartid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test"

    def test_delete_cart_by_cartid_events_by_eventid(self, client):
        client._client.delete.return_value.json.return_value = {}
        client.delete_cart_by_cartid_events_by_eventid("test", "test")
        client._client.delete.assert_called_once()
        assert client._client.delete.call_args[0][0] == "/cart/test/events/test"

    def test_get_cart_by_cartid_events_by_eventid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_cart_by_cartid_events_by_eventid("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test/events/test"

    def test_post_cart_by_cartid_events_by_eventid(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_cart_by_cartid_events_by_eventid("test", "test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/cart/test/events/test"

    def test_post_cart_by_cartid_events_by_eventid_attendees(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_cart_by_cartid_events_by_eventid_attendees("test", "test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/cart/test/events/test/attendees"

    def test_delete_cart_by_cartid_events_by_eventid_attendees_by_attendeeid(self, client):
        client._client.delete.return_value.json.return_value = {}
        client.delete_cart_by_cartid_events_by_eventid_attendees_by_attendeeid("test", "test", "test")
        client._client.delete.assert_called_once()
        assert client._client.delete.call_args[0][0] == "/cart/test/events/test/attendees/test"

    def test_get_cart_by_cartid_events_by_eventid_attendees_by_attendeeid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_cart_by_cartid_events_by_eventid_attendees_by_attendeeid("test", "test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test/events/test/attendees/test"

    def test_post_cart_by_cartid_events_by_eventid_attendees_by_attendeeid(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_cart_by_cartid_events_by_eventid_attendees_by_attendeeid("test", "test", "test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/cart/test/events/test/attendees/test"

    def test_get_cart_by_cartid_events_by_eventid_attendees_by_attendeeid_form(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_cart_by_cartid_events_by_eventid_attendees_by_attendeeid_form("test", "test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test/events/test/attendees/test/form"

    def test_post_cart_by_cartid_events_by_eventid_attendees_by_attendeeid_form(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_cart_by_cartid_events_by_eventid_attendees_by_attendeeid_form("test", "test", "test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/cart/test/events/test/attendees/test/form"

    def test_get_cart_by_cartid_events_by_eventid_form(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_cart_by_cartid_events_by_eventid_form("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test/events/test/form"

    def test_post_cart_by_cartid_events_by_eventid_form(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_cart_by_cartid_events_by_eventid_form("test", "test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/cart/test/events/test/form"

    def test_get_cart_by_cartid_events_by_eventid_forms(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_cart_by_cartid_events_by_eventid_forms("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test/events/test/forms"

    def test_get_cart_by_cartid_lookup(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_cart_by_cartid_lookup("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/test/lookup"

    def test_post_cart_by_cartid_promotions(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_cart_by_cartid_promotions("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/cart/test/promotions"

    def test_delete_cart_by_cartid_promotions_by_promotionid(self, client):
        client._client.delete.return_value.json.return_value = {}
        client.delete_cart_by_cartid_promotions_by_promotionid("test", "test")
        client._client.delete.assert_called_once()
        assert client._client.delete.call_args[0][0] == "/cart/test/promotions/test"

    def test_get_cart_id(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_cart_id()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/cart/id"

class TestClients:

    def test_get_clients(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_clients()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/clients"

    def test_get_clients_by_clientid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_clients_by_clientid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/clients/test"

    def test_get_clients_by_clientid_theme(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_clients_by_clientid_theme("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/clients/test/theme"

class TestData:

    def test_get_data_by_id(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_data_by_id("00000000-0000-0000-0000-000000000000")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/data/00000000-0000-0000-0000-000000000000"

class TestEvents:

    def test_get_events(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events"

    def test_post_events(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_events(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/events"

    def test_delete_events_by_eventid(self, client):
        client._client.delete.return_value.json.return_value = {}
        client.delete_events_by_eventid("test")
        client._client.delete.assert_called_once()
        assert client._client.delete.call_args[0][0] == "/events/test"

    def test_get_events_by_eventid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_events_by_eventid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test"

    def test_post_events_by_eventid_archive(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_events_by_eventid_archive("test")
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/events/test/archive"

    def test_get_events_by_eventid_bestseats(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_bestseats("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/bestseats"

    def test_get_events_by_eventid_communities(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_communities("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/communities"

    def test_get_events_by_eventid_data(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_events_by_eventid_data("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/data"

    def test_get_events_by_eventid_details(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_events_by_eventid_details("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/details"

    def test_get_events_by_eventid_documents(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_events_by_eventid_documents("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/documents"

    def test_get_events_by_eventid_fieldmetadata(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_fieldmetadata("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/fieldmetadata"

    def test_get_events_by_eventid_fields(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_fields("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/fields"

    def test_get_events_by_eventid_fields_by_fieldid_remotevalidate(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_events_by_eventid_fields_by_fieldid_remotevalidate("00000000-0000-0000-0000-000000000000", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/fields/00000000-0000-0000-0000-000000000000/remotevalidate"

    def test_get_events_by_eventid_groups(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_groups("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/groups"

    def test_get_events_by_eventid_lookup(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_lookup("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/lookup"

    def test_post_events_by_eventid_move(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_events_by_eventid_move("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/events/test/move"

    def test_get_events_by_eventid_orders(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_orders("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/orders"

    def test_get_events_by_eventid_paymentmethods(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_paymentmethods("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/paymentmethods"

    def test_get_events_by_eventid_reports_by_reportid(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_events_by_eventid_reports_by_reportid("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/reports/test"

    def test_get_events_by_eventid_resources(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_resources("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/resources"

    def test_post_events_by_eventid_restore(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_events_by_eventid_restore("test")
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/events/test/restore"

    def test_get_events_by_eventid_sections(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_sections("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/sections"

    def test_get_events_by_eventid_sections_by_sectionid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_events_by_eventid_sections_by_sectionid("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/sections/test"

    def test_get_events_by_eventid_sections_by_sectionid_seats(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_sections_by_sectionid_seats("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/sections/test/seats"

    def test_get_events_by_eventid_sessions(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_sessions("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/sessions"

    def test_get_events_by_eventid_theme(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_events_by_eventid_theme("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/theme"

    def test_get_events_by_eventid_types(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventid_types("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/test/types"

    def test_get_events_by_eventnumber_fields_by_fieldid_remotefetch(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_events_by_eventnumber_fields_by_fieldid_remotefetch(1, "00000000-0000-0000-0000-000000000000")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/events/1/fields/00000000-0000-0000-0000-000000000000/remotefetch"

    def test_post_events_copy(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_events_copy(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/events/copy"

class TestExchanges:

    def test_post_exchanges(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_exchanges(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/exchanges"

    def test_delete_exchanges_by_exchangeid(self, client):
        client._client.delete.return_value.json.return_value = {}
        client.delete_exchanges_by_exchangeid("test")
        client._client.delete.assert_called_once()
        assert client._client.delete.call_args[0][0] == "/exchanges/test"

    def test_get_exchanges_by_exchangeid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_exchanges_by_exchangeid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/exchanges/test"

    def test_put_exchanges_by_exchangeid(self, client):
        client._client.put.return_value.json.return_value = {}
        client.put_exchanges_by_exchangeid("test", MagicMock())
        client._client.put.assert_called_once()
        assert client._client.put.call_args[0][0] == "/exchanges/test"

class TestGroups:

    def test_post_groups(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_groups(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/groups"

    def test_put_groups(self, client):
        client._client.put.return_value.json.return_value = {}
        client.put_groups(MagicMock())
        client._client.put.assert_called_once()
        assert client._client.put.call_args[0][0] == "/groups"

    def test_get_groups_by_groupid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_groups_by_groupid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/groups/test"

    def test_post_groups_by_groupid_community(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_groups_by_groupid_community("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/groups/test/community"

    def test_get_groups_by_groupid_fields(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_groups_by_groupid_fields("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/groups/test/fields"

    def test_post_groups_by_groupid_fields(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_groups_by_groupid_fields("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/groups/test/fields"

    def test_get_groups_by_groupid_print(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_groups_by_groupid_print("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/groups/test/print"

    def test_get_groups_helpdesk_by_email(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_groups_helpdesk_by_email("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/groups/helpdesk/test"

    def test_post_groups_print(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_groups_print(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/groups/print"

class TestHooks:

    def test_get_hooks_list(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_hooks_list()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/hooks/list"

    def test_get_hooks_ping(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_hooks_ping()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/hooks/ping"

    def test_get_hooks_poll(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_hooks_poll()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/hooks/poll"

    def test_get_hooks_sample(self, client):
        client._client.get.return_value.json.return_value = None
        client.get_hooks_sample()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/hooks/sample"

    def test_post_hooks_subscribe(self, client):
        client._client.post.return_value.json.return_value = None
        client.post_hooks_subscribe(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/hooks/subscribe"

    def test_post_hooks_unsubscribe(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_hooks_unsubscribe(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/hooks/unsubscribe"

    def test_put_hooks_update(self, client):
        client._client.put.return_value.json.return_value = {}
        client.put_hooks_update(MagicMock())
        client._client.put.assert_called_once()
        assert client._client.put.call_args[0][0] == "/hooks/update"

class TestLookups:

    def test_post_lookups(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_lookups(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/lookups"

    def test_get_lookups_by_lookupid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_lookups_by_lookupid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/lookups/test"

    def test_get_lookups_by_lookupid_events_by_eventnumber(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_lookups_by_lookupid_events_by_eventnumber("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/lookups/test/events/1"

    def test_get_lookups_by_lookupid_events_by_eventnumber_attendees(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_lookups_by_lookupid_events_by_eventnumber_attendees("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/lookups/test/events/1/attendees"

    def test_get_lookups_by_lookupid_events_by_eventnumber_group(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_lookups_by_lookupid_events_by_eventnumber_group("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/lookups/test/events/1/group"

    def test_get_lookups_by_lookupid_events_by_eventnumber_orders(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_lookups_by_lookupid_events_by_eventnumber_orders("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/lookups/test/events/1/orders"

class TestOrders:

    def test_get_orders(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_orders()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/orders"

    def test_post_orders(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_orders(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders"

    def test_get_orders_by_orderid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_orders_by_orderid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/orders/test"

    def test_get_orders_by_orderid_fields(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_orders_by_orderid_fields("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/orders/test/fields"

    def test_post_orders_by_orderid_fields(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_orders_by_orderid_fields("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/test/fields"

    def test_get_orders_by_orderid_print(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_orders_by_orderid_print("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/orders/test/print"

    def test_post_orders_by_orderid_resend(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_orders_by_orderid_resend("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/test/resend"

    def test_post_orders_direct(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_orders_direct(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/direct"

    def test_get_orders_helpdesk_by_email(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_orders_helpdesk_by_email("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/orders/helpdesk/test"

    def test_post_orders_pos(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_orders_pos(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/pos"

    def test_post_orders_print(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_orders_print(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/print"

    def test_post_orders_reader_start(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_orders_reader_start(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/reader/start"

    def test_post_orders_sms(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_orders_sms(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/orders/sms"

class TestPaymentProfiles:

    def test_get_paymentprofiles(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_paymentprofiles()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/paymentprofiles"

    def test_get_paymentprofiles_by_paymentprofileid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_paymentprofiles_by_paymentprofileid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/paymentprofiles/test"

    def test_get_paymentprofiles_by_paymentprofileid_locations(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_paymentprofiles_by_paymentprofileid_locations("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/paymentprofiles/test/locations"

    def test_get_paymentprofiles_by_paymentprofileid_terminals(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_paymentprofiles_by_paymentprofileid_terminals("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/paymentprofiles/test/terminals"

    def test_post_paymentprofiles_by_paymentprofileid_terminals(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_paymentprofiles_by_paymentprofileid_terminals("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/paymentprofiles/test/terminals"

class TestPromotions:

    def test_get_promotions(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_promotions()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/promotions"

    def test_get_promotions_by_promotionid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_promotions_by_promotionid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/promotions/test"

    def test_post_promotions_dynamic(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_promotions_dynamic(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/promotions/dynamic"

    def test_post_promotions_import(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_promotions_import(MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/promotions/import"

class TestRegions:

    def test_get_regions(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_regions()
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/regions"

class TestSessions:

    def test_get_sessions_by_sessionid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_sessions_by_sessionid("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/sessions/test"

    def test_get_sessions_by_sessionid_attendees(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_sessions_by_sessionid_attendees("test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/sessions/test/attendees"

    def test_post_sessions_by_sessionid_checkin(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_sessions_by_sessionid_checkin("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/sessions/test/checkin"

    def test_post_sessions_by_sessionid_checkout(self, client):
        client._client.post.return_value.json.return_value = []
        client.post_sessions_by_sessionid_checkout("test", MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/sessions/test/checkout"

    def test_get_sessions_by_sessionid_email_by_email(self, client):
        client._client.get.return_value.json.return_value = []
        client.get_sessions_by_sessionid_email_by_email("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/sessions/1/email/test"

    def test_get_sessions_by_sessionid_flex_by_attendeeid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_sessions_by_sessionid_flex_by_attendeeid("test", "test")
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/sessions/test/flex/test"

    def test_post_sessions_by_sessionid_flex_checkin(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_sessions_by_sessionid_flex_checkin(1, MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/sessions/1/flex/checkin"

    def test_post_sessions_by_sessionid_flex_checkout(self, client):
        client._client.post.return_value.json.return_value = {}
        client.post_sessions_by_sessionid_flex_checkout(1, MagicMock())
        client._client.post.assert_called_once()
        assert client._client.post.call_args[0][0] == "/sessions/1/flex/checkout"

    def test_get_sessions_by_sessionid_groups_by_groupid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_sessions_by_sessionid_groups_by_groupid("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/sessions/1/groups/test"

    def test_get_sessions_by_sessionid_orders_by_orderid(self, client):
        client._client.get.return_value.json.return_value = {}
        client.get_sessions_by_sessionid_orders_by_orderid("test", 1)
        client._client.get.assert_called_once()
        assert client._client.get.call_args[0][0] == "/sessions/1/orders/test"
